### ISSUE TITLE
Non-200 responses from EchoNest crash the app

### ISSUE THREAD

**Issue by todd-elvers** [todd-elvers/light-jockey#3]
**WHEN**
A request to EchoNest returns a 400-level status code

**THEN**
The application does not come crashing down when EchoNest has a hick-up or returns a 400 because we've made too many requests

**COS:**
- The application does not crash when EchoNest returns a 400

**Comment by todd-elvers** [comment]
Maybe we want the application to crash if EchoNest returns a 500 or so?  That could mean the internet is down or EchoNest is down or something.  Hmm....

**Comment by hscheib** [comment]
If it errors just have the lights default to the default random color/interval values. Like if the song doesn't exist in echonest or a 500, same thing?

**Comment by todd-elvers** [comment]
> If it errors just have the lights default to the default random color/interval values.

Yeah, that's probably the best we can do for now.  I'll implement this this weekend.

**Comment by todd-elvers** [comment]
A fix for this is on master, waiting to test it at Hunter's.

**(Note: Once we get past v1.0.0 we'll be making these changes on branches)**

**Comment by todd-elvers** [comment]
This issue has been resolved as of **ed7b91768be39df101339fd641209e5d39689247** on **master**.
